#!/bin/bash
FLAGS="-y --suppress-common-lines"

for NUM in {0000..0005}
do
    echo CZE/${NUM}_out.txt
    ./codeReview <CZE/${NUM}_in.txt >CZE/${NUM}_out.sq.txt
    diff CZE/${NUM}_out.txt CZE/${NUM}_out.sq.txt $FLAGS
done
