#!/bin/bash

flags="-y --text"

DIR="CZE"

for file in {0000..0004}
do
    ./simple <CZE/${file}_in.txt >CZE/${file}_out.st.txt
    echo $file
#    diff CZE/${file}_out.txt CZE/${file}_out.st.txt $flags
    python3 diffTool.py CZE/${file}_out.txt CZE/${file}_out.st.txt
done