#!/bin/bash

FLAGS="-y --suppress-common-lines"
TESTS=CZE
for NUM in {0000..0004}
do
    ./main <${TESTS}/${NUM}_in.txt >${TESTS}/${NUM}_out.st.txt
    echo ${TESTS}/${NUM}_out.txt
    diff ${TESTS}/${NUM}_out.txt ${TESTS}/${NUM}_out.st.txt ${FLAGS}
done
