#!/bin/bash

flags="-y --text --suppress-common-lines"

DIR="CZE"

for file in {0000..0003}
do
    ./main <CZE/${file}_in.txt | sort >CZE/${file}_out.st.txt
    cat CZE/${file}_out.txt | sort >tmpFile
    echo $file
    diff tmpFile CZE/${file}_out.st.txt $flags
done

rm tmpFile